version: "3.3"

services:
  backend:
    build: ./backend
    container_name: symfony_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db