version: "3.3"

services:
  backend:
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"
    command: sh -c "composer install --no-interaction --no-ansi --no-progress && php bin/console server:run 0.0.0.0:8000"




